In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import ipywidgets as widgets
from IPython.display import display

In [2]:
df_target = pd.read_csv("lucas_organic_carbon_target.csv")
df_test = pd.read_csv("lucas_organic_carbon_training_and_test_data.csv")

In [ ]:
df_target.head()

          x
0  very_low
1  very_low
2  very_low
3  moderate
4       low

In [ ]:
df_test.head()

,500.0,500.5,501.0,501.5,502.0,502.5,503.0,503.5,504.0,504.5,...,2495.0,2495.5,2496.0,2496.5,2497.0,2497.5,2498.0,2498.5,2499.0,2499.5
0,0.000276,0.000278,0.000280,0.000281,0.000283,0.000284,0.000286,0.000288,0.000289,0.000291,...,-0.000070,-0.000068,-0.000065,-0.000063,-0.000060,-0.000058,-0.000056,-0.000053,-0.000051,-0.000048
1,0.000351,0.000353,0.000355,0.000357,0.000358,0.000360,0.000362,0.000364,0.000366,0.000368,...,-0.000041,-0.000038,-0.000036,-0.000034,-0.000031,-0.000029,-0.000026,-0.000024,-0.000022,-0.000019
2,0.000330,0.000331,0.000333,0.000335,0.000337,0.000339,0.000341,0.000343,0.000344,0.000346,...,-0.000086,-0.000084,-0.000081,-0.000079,-0.000076,-0.000074,-0.000072,-0.000069,-0.000067,-0.000064
3,0.000300,0.000303,0.000305,0.000307,0.000309,0.000312,0.000314,0.000316,0.000318,0.000320,...,-0.000109,-0.000105,-0.000100,-0.000096,-0.000092,-0.000088,-0.000084,-0.000080,-0.000076,-0.000072
4,0.000388,0.000390,0.000391,0.000393,0.000395,0.000397,0.000399,0.000401,0.000403,0.000405,...,-0.000076,-0.000074,-0.000072,-0.000070,-0.000067,-0.000065,-0.000063,-0.000061,-0.000059,-0.000057